import type { BlogPost } from "@/types/blog";

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: "Exploring Nature's Beauty",
    slug: "exploring-natures-beauty",
    excerpt: "Discover the hidden wonders of natural landscapes",
    image: "/placeholder.svg?height=600&width=800",
    category: "Adventure Travel",
  },
  {
    id: 2,
    title: "Tactical Consulting",
    slug: "tactical-consulting",
    excerpt: "Strategic solutions for complex business challenges",
    bgColor: "bg-zinc-800",
    category: "Business",
  },
  {
    id: 3,
    title: "Modern Leadership Techniques",
    slug: "modern-leadership-techniques",
    excerpt: "Innovative approaches to leading teams in the digital age",
    image: "/placeholder.svg?height=400&width=600",
    category: "Leadership",
  },
  {
    id: 4,
    title: "Expert Mentorship",
    slug: "expert-mentorship",
    excerpt: "Learn from industry professionals and accelerate your career",
    bgColor: "bg-zinc-900",
    category: "Career Development",
  },
  {
    id: 5,
    title: "Bespoke Solutions",
    slug: "bespoke-solutions",
    excerpt: "Tailored specifically to your unique business needs",
    image: "/placeholder.svg?height=500&width=500",
    category: "Consulting",
  },
  {
    id: 6,
    title: "Sunset Reflections",
    slug: "sunset-reflections",
    excerpt: "Capturing the beauty of golden hour landscapes",
    image: "/placeholder.svg?height=800&width=600",
    category: "Photography",
  },
  {
    id: 7,
    title: "Digital Transformation",
    slug: "digital-transformation",
    excerpt: "Embracing technology for business growth and innovation",
    bgColor: "bg-zinc-800",
    category: "Technology",
  },
  {
    id: 8,
    title: "Sustainable Practices",
    slug: "sustainable-practices",
    excerpt: "Building a better future through responsible business practices",
    bgColor: "bg-emerald-900",
    category: "Sustainability",
  },
  {
    id: 9,
    title: "Mountain Expedition",
    slug: "mountain-expedition",
    excerpt: "Conquering peaks and pushing personal limits",
    image: "/placeholder.svg?height=600&width=800",
    category: "Adventure",
  },
  {
    id: 10,
    title: "Urban Architecture",
    slug: "urban-architecture",
    excerpt: "Exploring the design and aesthetics of city landscapes",
    image: "/placeholder.svg?height=700&width=500",
    category: "Design",
  },
  {
    id: 11,
    title: "Culinary Adventures",
    slug: "culinary-adventures",
    excerpt: "Discovering unique flavors from around the world",
    bgColor: "bg-amber-700",
    category: "Food & Travel",
  },
  {
    id: 12,
    title: "Mindfulness in the Workplace",
    slug: "mindfulness-workplace",
    excerpt: "Incorporating meditation and mindfulness for better productivity",
    bgColor: "bg-teal-800",
    category: "Wellness",
  },
];
