import type { Job } from "@/types/job"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA (Remote)",
    type: "Full-time",
    appliedDate: "2023-04-15",
    status: "interviewing",
    logo: "/placeholder.svg?height=80&width=80",
    lastUpdated: "2 days ago",
    salary: "$120K - $150K",
    timeline: [
      {
        title: "Application Submitted",
        date: "Apr 15, 2023",
        description: "Your application was received and is under review.",
      },
      {
        title: "Initial Screening",
        date: "Apr 18, 2023",
        description: "You passed the initial screening process.",
      },
      {
        title: "Technical Interview Scheduled",
        date: "Apr 25, 2023",
        description: "A technical interview has been scheduled for May 2nd.",
      },
    ],
    description:
      "Join TechCorp as a Senior Frontend Developer and lead our UI/UX initiatives. You'll work with cutting-edge technologies to build responsive, accessible web applications that delight our users. This role requires expertise in React, TypeScript, and modern frontend architecture.",
  },
  {
    id: "2",
    title: "UX/UI Designer",
    company: "Design Masters",
    location: "New York, NY",
    type: "Full-time",
    appliedDate: "2023-04-10",
    status: "rejected",
    logo: "/placeholder.svg?height=80&width=80",
    lastUpdated: "1 week ago",
    salary: "$90K - $110K",
    timeline: [
      {
        title: "Application Submitted",
        date: "Apr 10, 2023",
        description: "Your application was received and is under review.",
      },
      {
        title: "Application Rejected",
        date: "Apr 17, 2023",
        description: "Thank you for your interest. We've decided to proceed with other candidates.",
      },
    ],
  },
  {
    id: "3",
    title: "Full Stack Engineer",
    company: "Startup Innovate",
    location: "Austin, TX (Hybrid)",
    type: "Full-time",
    appliedDate: "2023-04-18",
    status: "applied",
    logo: "/placeholder.svg?height=80&width=80",
    lastUpdated: "3 days ago",
    salary: "$100K - $130K",
    timeline: [
      {
        title: "Application Submitted",
        date: "Apr 18, 2023",
        description: "Your application was received and is under review.",
      },
    ],
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "Cloud Solutions",
    location: "Remote",
    type: "Contract",
    appliedDate: "2023-04-05",
    status: "offered",
    logo: "/placeholder.svg?height=80&width=80",
    lastUpdated: "Yesterday",
    salary: "$140K - $160K",
    timeline: [
      {
        title: "Application Submitted",
        date: "Apr 5, 2023",
        description: "Your application was received and is under review.",
      },
      {
        title: "Initial Screening",
        date: "Apr 8, 2023",
        description: "You passed the initial screening process.",
      },
      {
        title: "Technical Interview",
        date: "Apr 15, 2023",
        description: "You successfully completed the technical interview.",
      },
      {
        title: "Final Interview",
        date: "Apr 20, 2023",
        description: "You met with the team lead and engineering manager.",
      },
      {
        title: "Offer Extended",
        date: "Apr 25, 2023",
        description: "Congratulations! An offer has been extended to you.",
      },
    ],
  },
  {
    id: "5",
    title: "Product Manager",
    company: "Product Pioneers",
    location: "Seattle, WA",
    type: "Full-time",
    appliedDate: "2023-04-12",
    status: "interviewing",
    logo: "/placeholder.svg?height=80&width=80",
    lastUpdated: "4 days ago",
    salary: "$130K - $150K",
    timeline: [
      {
        title: "Application Submitted",
        date: "Apr 12, 2023",
        description: "Your application was received and is under review.",
      },
      {
        title: "Initial Screening",
        date: "Apr 16, 2023",
        description: "You passed the initial screening process.",
      },
      {
        title: "First Interview Scheduled",
        date: "Apr 22, 2023",
        description: "A first-round interview has been scheduled for Apr 28th.",
      },
    ],
  },
  {
    id: "6",
    title: "Data Scientist",
    company: "Data Insights",
    location: "Boston, MA (Remote)",
    type: "Full-time",
    appliedDate: "2023-04-08",
    status: "applied",
    logo: "/placeholder.svg?height=80&width=80",
    lastUpdated: "1 week ago",
    salary: "$115K - $140K",
    timeline: [
      {
        title: "Application Submitted",
        date: "Apr 8, 2023",
        description: "Your application was received and is under review.",
      },
    ],
  },
]
